<?php
/**
 * Country Configuration
 *
 * @package CERCHECW\SurveyFraudPrevention
 */

return [
    'AF' => ['name' => 'Afghanistan', 'phone' => '+93', 'prefix' => '93'],
    'AL' => ['name' => 'Albania', 'phone' => '+355', 'prefix' => '355'],
    'DZ' => ['name' => 'Algeria', 'phone' => '+213', 'prefix' => '213'],
    'AD' => ['name' => 'Andorra', 'phone' => '+376', 'prefix' => '376'],
    'AO' => ['name' => 'Angola', 'phone' => '+244', 'prefix' => '244'],
    'AG' => ['name' => 'Antigua and Barbuda', 'phone' => '+1268', 'prefix' => '1268'],
    'AR' => ['name' => 'Argentina', 'phone' => '+54', 'prefix' => '54'],
    'AM' => ['name' => 'Armenia', 'phone' => '+374', 'prefix' => '374'],
    'AU' => ['name' => 'Australia', 'phone' => '+61', 'prefix' => '61'],
    'AT' => ['name' => 'Austria', 'phone' => '+43', 'prefix' => '43'],
    'AZ' => ['name' => 'Azerbaijan', 'phone' => '+994', 'prefix' => '994'],
    'BS' => ['name' => 'Bahamas', 'phone' => '+1242', 'prefix' => '1242'],
    'BH' => ['name' => 'Bahrain', 'phone' => '+973', 'prefix' => '973'],
    'BD' => ['name' => 'Bangladesh', 'phone' => '+880', 'prefix' => '880'],
    'BB' => ['name' => 'Barbados', 'phone' => '+1246', 'prefix' => '1246'],
    'BY' => ['name' => 'Belarus', 'phone' => '+375', 'prefix' => '375'],
    'BE' => ['name' => 'Belgium', 'phone' => '+32', 'prefix' => '32'],
    'BZ' => ['name' => 'Belize', 'phone' => '+501', 'prefix' => '501'],
    'BJ' => ['name' => 'Benin', 'phone' => '+229', 'prefix' => '229'],
    'BT' => ['name' => 'Bhutan', 'phone' => '+975', 'prefix' => '975'],
    'BO' => ['name' => 'Bolivia', 'phone' => '+591', 'prefix' => '591'],
    'BA' => ['name' => 'Bosnia and Herzegovina', 'phone' => '+387', 'prefix' => '387'],
    'BW' => ['name' => 'Botswana', 'phone' => '+267', 'prefix' => '267'],
    'BR' => ['name' => 'Brazil', 'phone' => '+55', 'prefix' => '55'],
    'BN' => ['name' => 'Brunei', 'phone' => '+673', 'prefix' => '673'],
    'BG' => ['name' => 'Bulgaria', 'phone' => '+359', 'prefix' => '359'],
    'BF' => ['name' => 'Burkina Faso', 'phone' => '+226', 'prefix' => '226'],
    'BI' => ['name' => 'Burundi', 'phone' => '+257', 'prefix' => '257'],
    'CV' => ['name' => 'Cabo Verde', 'phone' => '+238', 'prefix' => '238'],
    'KH' => ['name' => 'Cambodia', 'phone' => '+855', 'prefix' => '855'],
    'CM' => ['name' => 'Cameroon', 'phone' => '+237', 'prefix' => '237'],
    'CA' => ['name' => 'Canada', 'phone' => '+1', 'prefix' => '1'],
    'CF' => ['name' => 'Central African Republic', 'phone' => '+236', 'prefix' => '236'],
    'TD' => ['name' => 'Chad', 'phone' => '+235', 'prefix' => '235'],
    'CL' => ['name' => 'Chile', 'phone' => '+56', 'prefix' => '56'],
    'CN' => ['name' => 'China', 'phone' => '+86', 'prefix' => '86'],
    'CO' => ['name' => 'Colombia', 'phone' => '+57', 'prefix' => '57'],
    'KM' => ['name' => 'Comoros', 'phone' => '+269', 'prefix' => '269'],
    'CG' => ['name' => 'Congo', 'phone' => '+242', 'prefix' => '242'],
    'CD' => ['name' => 'Congo (DRC)', 'phone' => '+243', 'prefix' => '243'],
    'CR' => ['name' => 'Costa Rica', 'phone' => '+506', 'prefix' => '506'],
    'CI' => ["name" => "Côte d'Ivoire", 'phone' => '+225', 'prefix' => '225'],
    'HR' => ['name' => 'Croatia', 'phone' => '+385', 'prefix' => '385'],
    'CU' => ['name' => 'Cuba', 'phone' => '+53', 'prefix' => '53'],
    'CY' => ['name' => 'Cyprus', 'phone' => '+357', 'prefix' => '357'],
    'CZ' => ['name' => 'Czechia', 'phone' => '+420', 'prefix' => '420'],
    'DK' => ['name' => 'Denmark', 'phone' => '+45', 'prefix' => '45'],
    'DJ' => ['name' => 'Djibouti', 'phone' => '+253', 'prefix' => '253'],
    'DM' => ['name' => 'Dominica', 'phone' => '+1767', 'prefix' => '1767'],
    'DO' => ['name' => 'Dominican Republic', 'phone' => '+1809', 'prefix' => '1809'],
    'EC' => ['name' => 'Ecuador', 'phone' => '+593', 'prefix' => '593'],
    'EG' => ['name' => 'Egypt', 'phone' => '+20', 'prefix' => '20'],
    'SV' => ['name' => 'El Salvador', 'phone' => '+503', 'prefix' => '503'],
    'GQ' => ['name' => 'Equatorial Guinea', 'phone' => '+240', 'prefix' => '240'],
    'ER' => ['name' => 'Eritrea', 'phone' => '+291', 'prefix' => '291'],
    'EE' => ['name' => 'Estonia', 'phone' => '+372', 'prefix' => '372'],
    'SZ' => ['name' => 'Eswatini', 'phone' => '+268', 'prefix' => '268'],
    'ET' => ['name' => 'Ethiopia', 'phone' => '+251', 'prefix' => '251'],
    'FJ' => ['name' => 'Fiji', 'phone' => '+679', 'prefix' => '679'],
    'FI' => ['name' => 'Finland', 'phone' => '+358', 'prefix' => '358'],
    'FR' => ['name' => 'France', 'phone' => '+33', 'prefix' => '33'],
    'GA' => ['name' => 'Gabon', 'phone' => '+241', 'prefix' => '241'],
    'GM' => ['name' => 'Gambia', 'phone' => '+220', 'prefix' => '220'],
    'GE' => ['name' => 'Georgia', 'phone' => '+995', 'prefix' => '995'],
    'DE' => ['name' => 'Germany', 'phone' => '+49', 'prefix' => '49'],
    'GH' => ['name' => 'Ghana', 'phone' => '+233', 'prefix' => '233'],
    'GR' => ['name' => 'Greece', 'phone' => '+30', 'prefix' => '30'],
    'GD' => ['name' => 'Grenada', 'phone' => '+1473', 'prefix' => '1473'],
    'GT' => ['name' => 'Guatemala', 'phone' => '+502', 'prefix' => '502'],
    'GN' => ['name' => 'Guinea', 'phone' => '+224', 'prefix' => '224'],
    'GW' => ['name' => 'Guinea-Bissau', 'phone' => '+245', 'prefix' => '245'],
    'GY' => ['name' => 'Guyana', 'phone' => '+592', 'prefix' => '592'],
    'HT' => ['name' => 'Haiti', 'phone' => '+509', 'prefix' => '509'],
    'HN' => ['name' => 'Honduras', 'phone' => '+504', 'prefix' => '504'],
    'HU' => ['name' => 'Hungary', 'phone' => '+36', 'prefix' => '36'],
    'IS' => ['name' => 'Iceland', 'phone' => '+354', 'prefix' => '354'],
    'IN' => ['name' => 'India', 'phone' => '+91', 'prefix' => '91'],
    'ID' => ['name' => 'Indonesia', 'phone' => '+62', 'prefix' => '62'],
    'IR' => ['name' => 'Iran', 'phone' => '+98', 'prefix' => '98'],
    'IQ' => ['name' => 'Iraq', 'phone' => '+964', 'prefix' => '964'],
    'IE' => ['name' => 'Ireland', 'phone' => '+353', 'prefix' => '353'],
    'IL' => ['name' => 'Israel', 'phone' => '+972', 'prefix' => '972'],
    'IT' => ['name' => 'Italy', 'phone' => '+39', 'prefix' => '39'],
    'JM' => ['name' => 'Jamaica', 'phone' => '+1876', 'prefix' => '1876'],
    'JP' => ['name' => 'Japan', 'phone' => '+81', 'prefix' => '81'],
    'JO' => ['name' => 'Jordan', 'phone' => '+962', 'prefix' => '962'],
    'KZ' => ['name' => 'Kazakhstan', 'phone' => '+7', 'prefix' => '7'],
    'KE' => ['name' => 'Kenya', 'phone' => '+254', 'prefix' => '254'],
    'KI' => ['name' => 'Kiribati', 'phone' => '+686', 'prefix' => '686'],
    'KW' => ['name' => 'Kuwait', 'phone' => '+965', 'prefix' => '965'],
    'KG' => ['name' => 'Kyrgyzstan', 'phone' => '+996', 'prefix' => '996'],
    'LA' => ['name' => 'Laos', 'phone' => '+856', 'prefix' => '856'],
    'LV' => ['name' => 'Latvia', 'phone' => '+371', 'prefix' => '371'],
    'LB' => ['name' => 'Lebanon', 'phone' => '+961', 'prefix' => '961'],
    'LS' => ['name' => 'Lesotho', 'phone' => '+266', 'prefix' => '266'],
    'LR' => ['name' => 'Liberia', 'phone' => '+231', 'prefix' => '231'],
    'LY' => ['name' => 'Libya', 'phone' => '+218', 'prefix' => '218'],
    'LI' => ['name' => 'Liechtenstein', 'phone' => '+423', 'prefix' => '423'],
    'LT' => ['name' => 'Lithuania', 'phone' => '+370', 'prefix' => '370'],
    'LU' => ['name' => 'Luxembourg', 'phone' => '+352', 'prefix' => '352'],
    'MG' => ['name' => 'Madagascar', 'phone' => '+261', 'prefix' => '261'],
    'MW' => ['name' => 'Malawi', 'phone' => '+265', 'prefix' => '265'],
    'MY' => ['name' => 'Malaysia', 'phone' => '+60', 'prefix' => '60'],
    'MV' => ['name' => 'Maldives', 'phone' => '+960', 'prefix' => '960'],
    'ML' => ['name' => 'Mali', 'phone' => '+223', 'prefix' => '223'],
    'MT' => ['name' => 'Malta', 'phone' => '+356', 'prefix' => '356'],
    'MH' => ['name' => 'Marshall Islands', 'phone' => '+692', 'prefix' => '692'],
    'MR' => ['name' => 'Mauritania', 'phone' => '+222', 'prefix' => '222'],
    'MU' => ['name' => 'Mauritius', 'phone' => '+230', 'prefix' => '230'],
    'MX' => ['name' => 'Mexico', 'phone' => '+52', 'prefix' => '52'],
    'FM' => ['name' => 'Micronesia', 'phone' => '+691', 'prefix' => '691'],
    'MD' => ['name' => 'Moldova', 'phone' => '+373', 'prefix' => '373'],
    'MC' => ['name' => 'Monaco', 'phone' => '+377', 'prefix' => '377'],
    'MN' => ['name' => 'Mongolia', 'phone' => '+976', 'prefix' => '976'],
    'ME' => ['name' => 'Montenegro', 'phone' => '+382', 'prefix' => '382'],
    'MA' => ['name' => 'Morocco', 'phone' => '+212', 'prefix' => '212'],
    'MZ' => ['name' => 'Mozambique', 'phone' => '+258', 'prefix' => '258'],
    'MM' => ['name' => 'Myanmar', 'phone' => '+95', 'prefix' => '95'],
    'NA' => ['name' => 'Namibia', 'phone' => '+264', 'prefix' => '264'],
    'NR' => ['name' => 'Nauru', 'phone' => '+674', 'prefix' => '674'],
    'NP' => ['name' => 'Nepal', 'phone' => '+977', 'prefix' => '977'],
    'NL' => ['name' => 'Netherlands', 'phone' => '+31', 'prefix' => '31'],
    'NZ' => ['name' => 'New Zealand', 'phone' => '+64', 'prefix' => '64'],
    'NI' => ['name' => 'Nicaragua', 'phone' => '+505', 'prefix' => '505'],
    'NE' => ['name' => 'Niger', 'phone' => '+227', 'prefix' => '227'],
    'NG' => ['name' => 'Nigeria', 'phone' => '+234', 'prefix' => '234'],
    'MK' => ['name' => 'North Macedonia', 'phone' => '+389', 'prefix' => '389'],
    'NO' => ['name' => 'Norway', 'phone' => '+47', 'prefix' => '47'],
    'OM' => ['name' => 'Oman', 'phone' => '+968', 'prefix' => '968'],
    'PK' => ['name' => 'Pakistan', 'phone' => '+92', 'prefix' => '92'],
    'PW' => ['name' => 'Palau', 'phone' => '+680', 'prefix' => '680'],
    'PA' => ['name' => 'Panama', 'phone' => '+507', 'prefix' => '507'],
    'PG' => ['name' => 'Papua New Guinea', 'phone' => '+675', 'prefix' => '675'],
    'PY' => ['name' => 'Paraguay', 'phone' => '+595', 'prefix' => '595'],
    'PE' => ['name' => 'Peru', 'phone' => '+51', 'prefix' => '51'],
    'PH' => ['name' => 'Philippines', 'phone' => '+63', 'prefix' => '63'],
    'PL' => ['name' => 'Poland', 'phone' => '+48', 'prefix' => '48'],
    'PT' => ['name' => 'Portugal', 'phone' => '+351', 'prefix' => '351'],
    'QA' => ['name' => 'Qatar', 'phone' => '+974', 'prefix' => '974'],
    'RO' => ['name' => 'Romania', 'phone' => '+40', 'prefix' => '40'],
    'RU' => ['name' => 'Russia', 'phone' => '+7', 'prefix' => '7'],
    'RW' => ['name' => 'Rwanda', 'phone' => '+250', 'prefix' => '250'],
    'KN' => ['name' => 'Saint Kitts and Nevis', 'phone' => '+1869', 'prefix' => '1869'],
    'LC' => ['name' => 'Saint Lucia', 'phone' => '+1758', 'prefix' => '1758'],
    'VC' => ['name' => 'Saint Vincent and the Grenadines', 'phone' => '+1784', 'prefix' => '1784'],
    'WS' => ['name' => 'Samoa', 'phone' => '+685', 'prefix' => '685'],
    'SM' => ['name' => 'San Marino', 'phone' => '+378', 'prefix' => '378'],
    'ST' => ['name' => 'Sao Tome and Principe', 'phone' => '+239', 'prefix' => '239'],
    'SA' => ['name' => 'Saudi Arabia', 'phone' => '+966', 'prefix' => '966'],
    'SN' => ['name' => 'Senegal', 'phone' => '+221', 'prefix' => '221'],
    'RS' => ['name' => 'Serbia', 'phone' => '+381', 'prefix' => '381'],
    'SC' => ['name' => 'Seychelles', 'phone' => '+248', 'prefix' => '248'],
    'SL' => ['name' => 'Sierra Leone', 'phone' => '+232', 'prefix' => '232'],
    'SG' => ['name' => 'Singapore', 'phone' => '+65', 'prefix' => '65'],
    'SK' => ['name' => 'Slovakia', 'phone' => '+421', 'prefix' => '421'],
    'SI' => ['name' => 'Slovenia', 'phone' => '+386', 'prefix' => '386'],
    'SB' => ['name' => 'Solomon Islands', 'phone' => '+677', 'prefix' => '677'],
    'SO' => ['name' => 'Somalia', 'phone' => '+252', 'prefix' => '252'],
    'ZA' => ['name' => 'South Africa', 'phone' => '+27', 'prefix' => '27'],
    'KR' => ['name' => 'South Korea', 'phone' => '+82', 'prefix' => '82'],
    'SS' => ['name' => 'South Sudan', 'phone' => '+211', 'prefix' => '211'],
    'ES' => ['name' => 'Spain', 'phone' => '+34', 'prefix' => '34'],
    'LK' => ['name' => 'Sri Lanka', 'phone' => '+94', 'prefix' => '94'],
    'SD' => ['name' => 'Sudan', 'phone' => '+249', 'prefix' => '249'],
    'SR' => ['name' => 'Suriname', 'phone' => '+597', 'prefix' => '597'],
    'SE' => ['name' => 'Sweden', 'phone' => '+46', 'prefix' => '46'],
    'CH' => ['name' => 'Switzerland', 'phone' => '+41', 'prefix' => '41'],
    'SY' => ['name' => 'Syria', 'phone' => '+963', 'prefix' => '963'],
    'TW' => ['name' => 'Taiwan', 'phone' => '+886', 'prefix' => '886'],
    'TJ' => ['name' => 'Tajikistan', 'phone' => '+992', 'prefix' => '992'],
    'TZ' => ['name' => 'Tanzania', 'phone' => '+255', 'prefix' => '255'],
    'TH' => ['name' => 'Thailand', 'phone' => '+66', 'prefix' => '66'],
    'TL' => ['name' => 'Timor-Leste', 'phone' => '+670', 'prefix' => '670'],
    'TG' => ['name' => 'Togo', 'phone' => '+228', 'prefix' => '228'],
    'TO' => ['name' => 'Tonga', 'phone' => '+676', 'prefix' => '676'],
    'TT' => ['name' => 'Trinidad and Tobago', 'phone' => '+1868', 'prefix' => '1868'],
    'TN' => ['name' => 'Tunisia', 'phone' => '+216', 'prefix' => '216'],
    'TR' => ['name' => 'Turkey', 'phone' => '+90', 'prefix' => '90'],
    'TM' => ['name' => 'Turkmenistan', 'phone' => '+993', 'prefix' => '993'],
    'TV' => ['name' => 'Tuvalu', 'phone' => '+688', 'prefix' => '688'],
    'UG' => ['name' => 'Uganda', 'phone' => '+256', 'prefix' => '256'],
    'UA' => ['name' => 'Ukraine', 'phone' => '+380', 'prefix' => '380'],
    'AE' => ['name' => 'United Arab Emirates', 'phone' => '+971', 'prefix' => '971'],
    'GB' => ['name' => 'United Kingdom', 'phone' => '+44', 'prefix' => '44'],
    'US' => ['name' => 'United States', 'phone' => '+1', 'prefix' => '1'],
    'UY' => ['name' => 'Uruguay', 'phone' => '+598', 'prefix' => '598'],
    'UZ' => ['name' => 'Uzbekistan', 'phone' => '+998', 'prefix' => '998'],
    'VU' => ['name' => 'Vanuatu', 'phone' => '+678', 'prefix' => '678'],
    'VA' => ['name' => 'Vatican City', 'phone' => '+379', 'prefix' => '379'],
    'VE' => ['name' => 'Venezuela', 'phone' => '+58', 'prefix' => '58'],
    'VN' => ['name' => 'Vietnam', 'phone' => '+84', 'prefix' => '84'],
    'YE' => ['name' => 'Yemen', 'phone' => '+967', 'prefix' => '967'],
    'ZM' => ['name' => 'Zambia', 'phone' => '+260', 'prefix' => '260'],
    'ZW' => ['name' => 'Zimbabwe', 'phone' => '+263', 'prefix' => '263'],
];
